---
collections:
  - name: ansible.controller
    version: 4.1.0
  - name: ansible.posix
    version: 1.3.0
  - name: community.general
    version: 4.3.0
  - name: containers.podman
    version: 1.9.0
#  - name: ansible.netcommon
#  - name: community.crypto
#  - name: community.mysql
