---
- name: Extract git variables to a file
  hosts: localhost
  vars_files:
    - no-keys.yml
  tasks:
    - name: Extract variables
      template:
        src: templates/tmp-git.j2
        dest: /tmp/git.txt
