ifndef::backend-docbook5,backend-docbook45[:imagesdir: ../../..]
[id='networkingress-lecture']
= Exposing Applications for External Access

== Kubernetes Ingress

Kubernetes assigns IP addresses to pods and services.
Pod and service IP addresses are not usually accessible outside of the cluster.
Unless prevented by network policies, the Kubernetes cluster typically allows internal communication between pods and services.
This internal commnication allows application pods to interact with services that are not externally accessible, such as database services.

For a web service that requires external access, create a Kubernetes ingress resource.
On its own, the ingress resource does not provide access.
The ingress resource interacts with the Kubernetes ingress controller to provide external access to a service over HTTP or HTTPS.

== Kubernetes Ingress Controller

Kubernetes supports multiple ingress controllers, and the Kubernetes project maintains the following ingress controllers:

AWS::
Use the AWS ingress controller if your Kubernetes cluster uses Amazon Web Services.

GCE::
Use the GCE ingress controller if your Kubernetes cluster uses Google Compute Engine.

nginx::
The nginx ingress controller is the default for `minikube`.

The implementation details for each ingress controller vary based on the type of Kubernetes cluster.
For example, run the `minikube addons enable ingress` command to enable the nginx ingress controller in a `minikube` environment.
Be aware that even this command depends on how the `minikube` environment is configured on your local machine.
Attempting to enable the ingress add-on when using the default `docker` driver results in the following error message:

----
$ minikube addons enable ingress

X  Exiting due to MK_USAGE: Due to networking limitations of driver docker on darwin, ingress addon is not supported.
Alternatively to use this addon you can use a vm-based driver:

  'minikube start --vm=true'

  To track the update on this work in progress feature please check:
  https://github.com/kubernetes/minikube/issues/7332
----

Configuring the `minikube` environment to use the `hyperkit` driver resolves this error.

----
$ minikube config set driver hyperkit
!  These changes will take effect upon a minikube delete and then a minikube start
----

Ingress controller pods run in a separate namespace.
Pod names and namespace names vary based on the type of ingress controller.
For example, in a `minikube` environment, the nginx ingress controller runs in the `ingress-nginx` namespace using the `ingress-nginx-controller` pod.

Your ability to see Kubernetes cluster resources, such as namespaces and pods, depends upon the permissions granted to your user.
Many developers do not have administrative permissions on their Kubernetes clusters and cannot view cluster resources.

Developer Sandbox for Red{nbsp}Hat OpenShift provides a development Kubernetes environment.
By default, OpenShift uses the HAProxy ingress controller.
This controller deploys resources to the `openshift-ingress` and `openshift-ingress-operator` namespaces.
Developers do not have permission to see the resources in these namespaces.

A list of available controllers can be found in the References section.

== Ingress Resource Configuration

The following is an example of an ingress resource.

----
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello  <1>
  annotations: <2>
    nginx.ingress.kubernetes.io/rewrite-target: / <3>
spec:
  rules:
    - host: hello.example.com <4>
      http:
        paths:
          - path: / <5>
            pathType: Prefix <6>
            backend:
              service:
                name: hello <7>
                port:
                  number: 8080 <8>
----

<1> The name of the ingress resource.
<2> A list of annotations for the ingress resource.
Annotations are required for some ingress controllers, such as nginx, but are not required for other ingress controllers, such as HAProxy.
Consult the documentation for the ingress controller used by your Kubernetes cluster.
<3> An individual nginx annotation.
The nginx ingress controller offers many ways to manipulate an incoming request and redirect it appropriately.
This annotation X...
The References section provides additional information about using nginx annotations.
<4> The host name used by external users to access your application.
During development, you might simulate ownership of the domain name by adding an entry to your local `hosts` file.
Production deployments must have DNS records pointing to your Kubernetes cluster.
<5> This value is used in combination with `pathType` to determine if the URL request matches the ingress resource.
A `path` value of `/` with the `pathType` value of `Prefix` is the equivalent of a wildcard that matches any path.
<6> This value is used in combination with `path` to determine if the URL request matches the ingress resource.
A `pathType` of `Prefix` offers a bit more flexibility allowing for matches where the `path` and the requested URL can contain either a trailing `/` or not.
A `pathType` of `Exact` requires the requested URL to exactly match the `path` value.
<7> The name of the service to which requests are redirected.
<8> The port number on which the service listens.

== Testing Your Ingress

Some stuff about testing your ingress.

== {nbsp}

[role="References"]
[NOTE]
====
https://kubernetes.io/docs/concepts/services-networking/ingress/[Ingress]

https://kubernetes.io/docs/concepts/services-networking/ingress-controllers/[Ingress Controllers]

https://github.com/kubernetes/ingress-nginx/blob/master/docs/examples/rewrite/README.md[Rewrite Annotation Reference]

// Template for a reference that does link to Red Hat Documentation.
For more information, refer to the _Automated Installation_ chapter in the _Red{nbsp}Hat Enterprise{nbsp}Linux{nbsp}7 Installation Guide_ at https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html-single/installation_guide/index#sect-automated-installation
====
