- name: Configure workstation VM
  hosts: localhost
  vars:
    tmp_git_file: /tmp/git.yml
    github_private: github_rsa
  tasks:
    - name: Check for {{ tmp_git_file }}
      stat:
        path: "{{ tmp_git_file }}"
      register: git_file

    - name: Fail if {{ tmp_git_file }} does not exist
      fail:
        msg: Variable file "{{ tmp_git_file }}" does not exist.
      when: git_file['stat']['exists'] | bool == False

    - name: Include the {{ tmp_git_file }} variables file
      include_vars: "{{ tmp_git_file }}"

    - name: Fail when git is not defined
      fail:
        msg: The "git" variable must be defined.
      when: git is not defined

    - block:
        - name: Verify that git repository exists
          stat:
            path: "{{ repo }}/.git"
          register: repo_exists

        - name: Fail if {{ repo }} is not a git repository
          fail:
            msg: "{{ repo }} is not a git repository."
          when: repo_exists['stat']['exists'] | bool == False

        - name: Configure basic git settings
          git_config:
            scope: local
            name: "{{ item['name'] }}"
            value: "{{ item['value'] }}"
            repo: "{{ repo }}"
          loop: "{{ git }}"
      when: repo is defined

    - name: Check for github SSH keys
      stat:
        path: /home/student/.ssh/{{ github_private }}
      register: github_keys

    - name: Configure global github settings with SSH keys
      vars:
        global_github:
          - name: "url.git@github.com:.insteadOf"
            value: "https://github.com/"
      git_config:
        scope: global
        name: "{{ item['name'] }}"
        value: "{{ item['value'] }}"
      loop: "{{ global_github }}"
      when: github_keys['stat']['exists'] | bool == True

    - name: Configure global github settings with HTTPS
      vars:
        global_github:
          - name: "credential.https://github.com.username"
            value: "angelesphillips"
          - name: "url.https://github.com/.insteadOf"
            value: "git@github.com:"
      git_config:
        scope: global
        name: "{{ item['name'] }}"
        value: "{{ item['value'] }}"
      loop: "{{ global_github }}"
      when: github_keys['stat']['exists'] | bool == False
