---
# Sample command from this directory with the `ansible-playbook` command:
# ansible-playbook prep_collections.yml --ask-vault-pass
# Sample command from this directory with the `ansible-navigator` command:
# ansible-navigator run prep_collections.yml -i inventory-ee --mode stdout --pae false --ask-vault-pass
- name: Add Automation Hub Token to ~/.bashrc
  hosts: workstation
  become: true
  gather_facts: false
  vars:
    the_user: student
  vars_files:
    - automation_hub_token.yml
  tasks:
    - name: Fail if automation_hub_token is not defined
      when: automation_hub_token is not defined
      ansible.builtin.fail:
        msg: >-
          The 'automation_hub_token' variable must be defined. Generate your
          token at https://console.redhat.com/ansible/automation-hub/token

    - name: Add automation hub token line
      become: true
      become_user: "{{ the_user }}"
      ansible.builtin.lineinfile:
        path: ~{{ the_user }}/.bashrc
        regexp: "^export ANSIBLE_GALAXY_SERVER_AUTOMATION_HUB_TOKEN"
        line: "export ANSIBLE_GALAXY_SERVER_AUTOMATION_HUB_TOKEN='{{ automation_hub_token }}'"
        owner: "{{ the_user }}"
        group: "{{ the_user }}"
        mode: "0644"
      register: add_token

    - name: Prevent token from expiring
      ansible.builtin.command:
        cmd: >
          curl https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
          -d grant_type=refresh_token
          -d client_id="cloud-services"
          -d refresh_token="{{ automation_hub_token }}"
          --fail --silent --show-error --output /dev/null
      no_log: true

    - name: Run 'source ~/.bashrc'
      when: add_token['changed'] | bool is true
      ansible.builtin.debug:
        msg: 'Use new bashrc settings: source ~/.bashrc'
