---
- name: Add Automation Hub Token to ~/.bashrc
  hosts: localhost
  become: false
  gather_facts: false
  vars:
    the_user: student
  vars_files:
    - automation_hub_token.yml
  tasks:
    - name: Add automation hub token line
      become: true
      become_user: "{{ the_user }}"
      lineinfile:
        path: "~{{ the_user }}/.bashrc"
        regexp: "^export ANSIBLE_GALAXY_SERVER_AUTOMATION_HUB_TOKEN"
        line: "export ANSIBLE_GALAXY_SERVER_AUTOMATION_HUB_TOKEN='{{ automation_hub_token }}'"
      register: add_token

    - name: Add RED_HAT_OFFLINE_TOKEN line
      become: true
      become_user: "{{ the_user }}"
      lineinfile:
        path: "~{{ the_user }}/.bashrc"
        regexp: "^export RED_HAT_OFFLINE_TOKEN"
        line: "export RED_HAT_OFFLINE_TOKEN='{{ red_hat_offline_token }}'"
      register: add_token

    - name: Run 'source ~/.bashrc'
      debug:
        msg: 'Use new bashrc settings: source ~/.bashrc'
      when: add_token['changed'] | bool == True
