---
- name: Prepare workstation for scaffolding
  hosts: localhost
  become: false
  gather_facts: true
  vars_files:
    - vars.yml
  tasks:
    - name: Create GitHub keys
      vars:
        the_key: "{{ github_keys | selectattr('type', '==', item) }}"
        the_key_content: "{{ the_key[0]['data'] }}"
        the_key_name: "{{ the_key[0]['name'] }}"
        the_key_mode: "{{ the_key[0]['mode'] }}"
      copy:
        content: "{{ the_key_content }}"
        dest: "{{ ansible_env['HOME'] }}/.ssh/{{ the_key_name }}"
        owner: "{{ ansible_env['LOGNAME'] }}"
        group: "{{ ansible_env['LOGNAME'] }}"
        mode: "{{ the_key_mode }}"
        setype: ssh_home_t
      loop:
        - "private"
        - "public"
      loop_control:
        label: Creating the '{{ ansible_env["HOME"] }}/.ssh/{{ the_key_name }}' GitHub file.

    - name: Update ~/.bash_profile
      blockinfile:
        path: "{{ ansible_env['HOME'] }}/.bash_profile"
        marker: "# {mark} ANSIBLE MANAGED BLOCK GITHUB"
        block: "{{ lookup('template', 'templates/bash_profile.j2') }}"
        insertafter: EOF
        owner: "{{ ansible_env['LOGNAME'] }}"
        group: "{{ ansible_env['LOGNAME'] }}"
        mode: '0644'
        state: present

    - name: Create {{ ansible_env['HOME'] }}/.ssh/config.d
      file:
        path: "{{ ansible_env['HOME'] }}/.ssh/config.d"
        owner: "{{ ansible_env['LOGNAME'] }}"
        group: "{{ ansible_env['LOGNAME'] }}"
        mode: '0775'
        state: directory

    - name: Add 'include' line to {{ ansible_env['HOME'] }}/.ssh/config
      lineinfile:
        path: "{{ ansible_env['HOME'] }}/.ssh/config"
        regexp: '^[Ii]nclude'
        line: 'include ~/.ssh/config.d/*.conf'
        insertbefore: BOF
        state: present

    - name: Update SSH configuration for GitHub Host
      blockinfile:
        path: "{{ ansible_env['HOME'] }}/.ssh/config.d/github.conf"
        marker: "# {mark} ANSIBLE MANAGED BLOCK GITHUB"
        block: "{{ lookup('template', 'templates/ssh_config.j2') }}"
        insertafter: EOF
        owner: "{{ ansible_env['LOGNAME'] }}"
        group: "{{ ansible_env['LOGNAME'] }}"
        mode: '0644'
        create: true
        state: present
        setype: ssh_home_t

    - name: Configure Git to use SSH instead of HTTPS for GitHub
      vars:
        github_ssh:
      command: git config --global --replace-all url."git@github.com:".insteadOf "https://github.com/"

    - name: Update ~/.ssh/config for wildcard Host
      lineinfile:
        path: "{{ ansible_env['HOME'] }}/.ssh/config"
        regexp: '^Host .$'
        line: "Host * !github.com"
        state: present
