---
# Sample command from this directory with the `ansible-playbook` command:
# ansible-playbook sk.yml --ask-vault-pass
# Sample command from this directory with the `ansible-navigator` command:
# ansible-navigator run sk.yml -i inventory-ee --mode stdout --pae false --ask-vault-pass
- name: Prepare workstation for scaffolding
  hosts: workstation
  become: true
  gather_facts: false
  vars:
    the_user: student
  vars_files:
    - vars.yml
  tasks:
    - name: Git block
      block:
        - name: Create GitHub keys
          ansible.builtin.copy:
            content: "{{ item['data'] }}"
            dest: ~{{ the_user }}/.ssh/{{ item['name'] }}
            owner: "{{ the_user }}"
            group: "{{ the_user }}"
            mode: "{{ item['mode'] }}"
            setype: ssh_home_t
          loop: "{{ github_keys }}"
          loop_control:
            label: Creating the '~{{ the_user }}/.ssh/{{ item["name"] }}' file.

        - name: Create ~{{ the_user }}/.ssh/config.d
          ansible.builtin.file:
            path: ~{{ the_user }}/.ssh/config.d
            owner: "{{ the_user }}"
            group: "{{ the_user }}"
            mode: '0775'
            state: directory

        - name: Add 'include' line to ~{{ the_user }}/.ssh/config
          ansible.builtin.lineinfile:
            path: ~{{ the_user }}/.ssh/config
            regexp: '^[Ii]nclude'
            line: 'include ~/.ssh/config.d/*.conf'
            insertbefore: BOF
            state: present

        - name: Update SSH configuration for GitHub Host
          ansible.builtin.blockinfile:
            path: ~{{ the_user }}/.ssh/config.d/github.conf
            marker: "# {mark} ANSIBLE MANAGED BLOCK GITHUB"
            block: "{{ lookup('template', 'templates/ssh_config.j2') }}"
            insertafter: EOF
            owner: "{{ the_user }}"
            group: "{{ the_user }}"
            mode: '0644'
            create: true
            state: present
            setype: ssh_home_t

        - name: Update SSH configuration for classroom
          ansible.builtin.copy:
            content: |
              Host classroom
                User instructor
                Port 22022
                UserKnownHostsFile /dev/null
                StrictHostKeyChecking no
                IdentityFile ~{{ the_user }}/.ssh/instructor_key
                LogLevel ERROR
                PreferredAuthentications publickey
            dest: ~{{ the_user }}/.ssh/config.d/classroom.conf
            owner: "{{ the_user }}"
            group: "{{ the_user }}"
            mode: '0644'
            setype: ssh_home_t

        - name: Update ~/.ssh/config for wildcard Host
          ansible.builtin.lineinfile:
            path: ~{{ the_user }}/.ssh/config
            regexp: '^Host .$'
            line: "Host * !github.com"
            state: present
      tags: git

- name: Configure Git
  vars:
    git_scope: global
  ansible.builtin.import_playbook: configure_git.yml

