---
- name: Check for minor distribution variable file
  ansible.builtin.stat:
    path: vars/{{ distribution_minor_version }}
  register: query_vars_minor

- name: >-
    Include file: vars/{{ distribution_minor_version }}
  when: query_vars_minor['stat']['exists'] | bool is true
  ansible.builtin.include_vars: vars/{{ distribution_minor_version }}

- name: Check for major distribution variable file
  when: query_vars_minor['stat']['exists'] | bool is false
  ansible.builtin.stat:
    path: vars/{{ distribution_major_version }}
  register: query_vars_major

- name: >-
    Include file: vars/{{ distribution_major_version }}
  when:
    - query_vars_minor['stat']['exists'] | bool is false
    - query_vars_major['stat']['exists'] | bool is true
  ansible.builtin.include_vars: ../vars/{{ distribution_major_version }}

- name: Check for minor distribution var file
  ansible.builtin.stat:
    path: vars/{{ distribution_minor_version }}
  register: query_vars_minor

- name: >-
    Include file: vars/{{ distribution_minor_version }}
  when: query_vars_minor['stat']['exists'] | bool is true
  ansible.builtin.include_vars: ../vars/{{ distribution_minor_version }}
