---
- name: Fail if git_vars_file is not defined
  fail:
    msg: The "git_vars_file" variable must be defined.
  when: git_vars_file is not defined

- name: Check for git_vars_file
  stat:
    path: "{{ git_vars_file }}"
  register: git_vars

- name: Fail if git_vars_file does not exist
  fail:
    msg: The "{{ git_vars_file }}" does not exist.
  when: git_vars['stat']['exists']|bool == False

- name: Include git_vars_file
  include_vars:
    file: "{{ git_vars_file }}"
    name: mygit

- name: Fail if mygit['git'] is not defined
  fail:
    msg: The "git" variable must be defined in the "{{ git_vars_file }}" file.
  when: mygit['git'] is not defined

- name: Fail if scope is not defined
  fail:
    msg: The "scope" variable must be defined.
  when: scope is not defined

- name: Configure global Git settings
  command: git config --{{ scope }} --replace-all {{ item['name'] }} {{ item['value'] }}
  loop: "{{ mygit['git'] }}"
  when: scope|lower == "global"

- name: Configure local Git settings
  command: git config --{{ scope }} --replace-all {{ item['name'] }} {{ item['value'] }}
  args:
    chdir: "{{ repo }}"
  loop: "{{ mygit['git'] }}"
  when:
    - scope|lower == "local"
    - repo is defined
