---
# Do this for RHEL 10
- name: Modify .bashrc to change PS1 prompt for git
  ansible.builtin.blockinfile:
    path: ~{{ the_user }}/.bashrc
    marker: "# {mark} ANSIBLE MANAGED BLOCK PS1"
    owner: "{{ the_user }}"
    group: "{{ the_user }}"
    mode: "0644"
    state: present
    block: "{{ lookup('file', 'files/bashrc_git_rhel10') }}"
  tags: ps1

- name: Update ~/.bash_profile
  ansible.builtin.blockinfile:
    path: ~{{ the_user }}/.bash_profile
    marker: "# {mark} ANSIBLE MANAGED BLOCK SECURITY"
    block: "{{ lookup('template', 'templates/bash_profile_rhel_10.j2') }}"
    insertafter: EOF
    owner: "{{ the_user }}"
    group: "{{ the_user }}"
    mode: "0644"
    state: present

# This list is still missing the screenshot application
- name: Set favorites
  become: true
  become_user: "{{ the_user }}"
  ansible.builtin.command:
    argv:
      - gsettings
      - set
      - org.gnome.shell
      - favorite-apps
      - "['firefox.desktop', 'org.gnome.Ptyxis.desktop', 'code.desktop', 'org.gnome.Nautilus.desktop', 'org.gnome.Screenshot.desktop']"
  changed_when: false
